from pathlib import Path

import yaml

from scripts.build_handler_map import build_handler_map


def test_build_handler_map_from_synthetic_suites(tmp_path: Path) -> None:
    first_script = tmp_path / "Common.suite" / "Scripts" / "common.script"
    second_script = (
        tmp_path / "EnoviaCommon.suite" / "Scripts" / "CommonEnovia.script"
    )
    first_script.parent.mkdir(parents=True)
    second_script.parent.mkdir(parents=True)
    first_script.write_text(
        "to clickElement label,SR\nend clickElement\n",
        encoding="utf-8",
    )
    second_script.write_text(
        "function commonScreenPart Portion\nend function\n",
        encoding="utf-8",
    )
    output = tmp_path / "output" / "handler_map.yaml"

    mapping = build_handler_map(str(tmp_path), str(output))
    loaded = yaml.safe_load(output.read_text(encoding="utf-8"))

    expected = {
        "clickElement": "Common.suite/Scripts/common.script",
        "commonScreenPart": "EnoviaCommon.suite/Scripts/CommonEnovia.script",
    }
    assert mapping == expected
    assert loaded == expected
    assert output.read_text(encoding="utf-8").startswith(
        "# Auto-generated by build_handler_map.py"
    )