from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from src.static.sensetalk_parser import handler_defs

KNOWN_PREFIXES = (
    "CommonEnovia",
    "common",
    "configEnovia",
    "LaunchApp",
    "FileOperations",
    "EnoviaSearch",
    "exceptionHandling",
    "CommonEnoviaContd",
    "EnoviaChangeManagement",
    "MQLTestData",
    "WINSCP",
)


def _script_files(repo_root: Path) -> list[Path]:
    scripts: list[Path] = []
    for script_path in repo_root.rglob("*.script"):
        relative_parts = script_path.relative_to(repo_root).parts
        for index, part in enumerate(relative_parts[:-1]):
            if part.casefold().endswith(".suite") and (
                index + 1 < len(relative_parts)
                and relative_parts[index + 1].casefold() == "scripts"
            ):
                scripts.append(script_path)
                break
    return sorted(scripts)


def build_handler_map(repo_root: str, output: str) -> dict[str, str]:
    root = Path(repo_root).resolve()
    mapping: dict[str, str] = {}
    for script_path in _script_files(root):
        source = script_path.read_text(encoding="utf-8", errors="replace")
        relative_path = script_path.relative_to(root).as_posix()
        for definition in handler_defs(source):
            mapping[definition.name] = relative_path

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_body = yaml.safe_dump(mapping, sort_keys=True, allow_unicode=True)
    output_path.write_text(
        "# Auto-generated by build_handler_map.py — do not edit manually\n"
        + yaml_body,
        encoding="utf-8",
    )
    return mapping


def _prefix_status(mapping: dict[str, str]) -> list[tuple[str, bool]]:
    handler_names = [name.casefold() for name in mapping]
    return [
        (
            prefix,
            any(
                name.startswith(prefix.casefold())
                or prefix.casefold().startswith(name)
                for name in handler_names
            ),
        )
        for prefix in KNOWN_PREFIXES
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the SenseTalk handler map.")
    parser.add_argument("repo_root")
    parser.add_argument(
        "--output",
        default="tracks/enovia/handler_map.yaml",
    )
    args = parser.parse_args()

    mapping = build_handler_map(args.repo_root, args.output)
    statuses = _prefix_status(mapping)
    print(f"Wrote {len(mapping)} handlers to {args.output}")
    for prefix, present in statuses:
        print(f"{'OK' if present else 'MISSING'}: {prefix}")
    print(f"Verified {sum(present for _, present in statuses)}/{len(statuses)} prefixes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
